// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeyBto58Xdkra8KoMcu0_SPCurKPHHiWs',
    appId: '1:1098857164841:web:a86260b90f842f2d8bac38',
    messagingSenderId: '1098857164841',
    projectId: 'frubix-6712a',
    authDomain: 'frubix-6712a.firebaseapp.com',
    storageBucket: 'frubix-6712a.firebasestorage.app',
    measurementId: 'G-D5N03TT55X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_zB51HpSi91AZ3eh84I4AukM3d-QfZgI',
    appId: '1:1098857164841:android:21c353e0baba03038bac38',
    messagingSenderId: '1098857164841',
    projectId: 'frubix-6712a',
    storageBucket: 'frubix-6712a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDqJMTXyFFiFlHINu7M6gPUIYexcBzzjE',
    appId: '1:1098857164841:ios:67438e9bb7e116948bac38',
    messagingSenderId: '1098857164841',
    projectId: 'frubix-6712a',
    storageBucket: 'frubix-6712a.firebasestorage.app',
    iosBundleId: 'com.example.frubix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDqJMTXyFFiFlHINu7M6gPUIYexcBzzjE',
    appId: '1:1098857164841:ios:67438e9bb7e116948bac38',
    messagingSenderId: '1098857164841',
    projectId: 'frubix-6712a',
    storageBucket: 'frubix-6712a.firebasestorage.app',
    iosBundleId: 'com.example.frubix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeyBto58Xdkra8KoMcu0_SPCurKPHHiWs',
    appId: '1:1098857164841:web:eb7a0db8b36441c18bac38',
    messagingSenderId: '1098857164841',
    projectId: 'frubix-6712a',
    authDomain: 'frubix-6712a.firebaseapp.com',
    storageBucket: 'frubix-6712a.firebasestorage.app',
    measurementId: 'G-H4Y2DJB09T',
  );
}
